# Generated by Django 4.0 on 2024-02-23 16:09

from django.db import migrations, models
import django.db.models.deletion
import listings.models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_blog_status_propertylisting_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to=listings.models.AboutUs.upload_to)),
                ('about', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to=listings.models.ContactUs.upload_to)),
                ('content', models.TextField(null=True)),
                ('location', models.CharField(max_length=500, null=True)),
                ('phone_number', models.TextField(null=True)),
                ('whatapp_link', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('icon', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='testimony',
            name='status',
            field=models.CharField(choices=[('published', 'Published'), ('draft', 'Draft')], default='draft', max_length=10),
        ),
        migrations.CreateModel(
            name='OurServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('icon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='listings.icon')),
            ],
        ),
    ]
