# Generated by Django 4.0 on 2024-06-14 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_remove_propertylisting_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertylisting',
            name='category',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
