# Generated by Django 4.0 on 2024-06-14 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_propertylisting_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('pending', 'pending'), ('expire', 'expire')], default='published', max_length=10),
        ),
        migrations.AlterField(
            model_name='propertylisting',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('pending', 'pending'), ('expire', 'expire')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('pending', 'pending'), ('expire', 'expire')], default='draft', max_length=10),
        ),
    ]
