# Generated by Django 4.0 on 2024-06-14 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='MostViewPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
